### ISSUE TITLE
Getting error with usage of MultisigAccountModificationTransaction

### ISSUE THREAD

**Issue by evias** [nemtech/symbol-sdk-typescript-javascript#626]
1. Expected behavior and actual behavior.

Expected: Using MultisigAccountModificationTransaction should be possible.
Actual: Usage of MultisigAccountModificationTransaction produces an error _at time of signature_.

```
TypeError: addition.encodeUnresolvedAddress is not a function
    at /.../node_modules/symbol-sdk/dist/src/model/transaction/MultisigAccountModificationTransaction.js:130:77
    at Array.map (<anonymous>)
    at MultisigAccountModificationTransaction.toEmbeddedTransaction (/.../node_modules/symbol-sdk/dist/src/model/transaction/MultisigAccountModificationTransaction.js:129:375)
    at /.../node_modules/symbol-sdk/dist/src/model/transaction/AggregateTransaction.js:199:86
    at Array.map (<anonymous>)
    at AggregateTransaction.createBuilder (/.../node_modules/symbol-sdk/dist/src/model/transaction/AggregateTransaction.js:199:53)
    at AggregateTransaction.generateBytes (/.../node_modules/symbol-sdk/dist/src/model/transaction/Transaction.js:307:21)
    at AggregateTransaction.signWith (/.../node_modules/symbol-sdk/dist/src/model/transaction/Transaction.js:156:44)
    at Account.sign (/.../node_modules/symbol-sdk/dist/src/model/account/Account.js:123:28)
```

2. Steps to reproduce the problem.

```
const account = Account.createFromPrivateKey('privateKey_for_TAWJ', NetworkType.TEST_NET)
const modifTx = MultisigAccountModificationTransaction.create(
            Deadline.create(),
            1, // 2 minimum cosignatories
            1, // 2 cosignatories needed for removal of cosignatory
            [Address.createFromRawAddress('TAWJ2M7BGKWGBPOUGD5NDKHYDDQ7OQD26HJMMQQ')],
            [],
            NetworkType.TEST_NET,
            UInt64.fromUint(1000000), // 1 XYM fee
        )

        // MultisigAccountModificationTransaction must be announced in aggregate bonded
        const aggregateTx = AggregateTransaction.createBonded(
            Deadline.create(),
            [modifTx.toAggregate(account.publicAccount)],
            this.networkType, [], UInt64.fromUint(1000000))

// this line produces the error shared above.
const signedAggregateTx = account.sign(aggregateTx, this.generationHash);
```

3. Specifications like the version of the project, operating system, or hardware.

Branch: master
Version: v0.20.7

**Comment by rg911** [comment]
Looks like you are using the wrong version of SDK.

latest version is 0.20.6

Also `Address.createFromRawAddress` does not take networkType anymore.

**Comment by evias** [comment]
Please look at the actual issue instead .... **master** is `0.20.7` in case you didn't know: https://github.com/nemtech/symbol-sdk-typescript-javascript/blob/master/package.json#L3

And this is also reproducible with 0.20.6.

**Comment by evias** [comment]
The Address.createFromRawAddress call was modified, error still happens.

**Comment by rg911** [comment]
master 0.20.7 is actually the same as 0.20.6 and you should use 0.20.6. and tested your codes, don't have issue at all here

**Comment by evias** [comment]
can you show me the transaction hash and payload of the transaction you signed?

**Comment by evias** [comment]
doesn't seem like a local problem as i was able to reproduce on different machine, too.

**Comment by rg911** [comment]
```
const account = Account.createFromPrivateKey(
  "C422CC3C9257A1568036E1726E64EB5923C8363A13D4344F9E66CD89C8789BC7",
  NetworkType.TEST_NET
);
const modifTx = MultisigAccountModificationTransaction.create(
  Deadline.create(),
  1, // 2 minimum cosignatories
  1, // 2 cosignatories needed for removal of cosignatory
  [Address.createFromRawAddress("TAWJ2M7BGKWGBPOUGD5NDKHYDDQ7OQD26HJMMQQ")],
  [],
  NetworkType.TEST_NET,
  UInt64.fromUint(1000000) // 1 XYM fee
);

// MultisigAccountModificationTransaction must be announced in aggregate bonded
const aggregateTx = AggregateTransaction.createBonded(
  Deadline.create(),
  [modifTx.toAggregate(account.publicAccount)],
  NetworkType.TEST_NET,
  [],
  UInt64.fromUint(1000000)
);

// this line produces the error shared above.
const signedAggregateTx = account.sign(
  aggregateTx,
  "FAF3F9FD3E32EB43273E5351BAE705D0179D37CBDCC4DD78A0C73232DD3EF32C"
);

console.log(signedAggregateTx);
```

```
SignedTransaction {
  payload: 'F8000000000000002A5566ABAAD9C6D4326768F6D31A4D43EEFFDB67FEF6E9B2D8F394A43CF6DE24BA7E543FE16ADB7C090BC5BC8221822304251337CB7E1E738EFDB568A06256012EBDFC5F4EF2058BF4B083FFE2B67AD89D96E27EE03F043FCC4FAB8ACD2FDFE1000000000198414240420F000000000021CBB3F204000000F117E1096360741EE1847E592A559C4AD4C54B998CF3C882D76F43F6A858D7A2500000000000000050000000000000002EBDFC5F4EF2058BF4B083FFE2B67AD89D96E27EE03F043FCC4FAB8ACD2FDFE100000000019855410101010000000000982C9D33E132AC60BDD430FAD1A8F818E1F7407AF1D2C642',
  hash: '9A8B0C08F28D7230A586C508641F169425D789F87291B8870328F190081085EA',
  signerPublicKey: '2EBDFC5F4EF2058BF4B083FFE2B67AD89D96E27EE03F043FCC4FAB8ACD2FDFE1',
  type: 16961,
  networkType: 152
}
```

**Comment by evias** [comment]
Interesting, i now confirm on my side that re-installing the SDK on said project seems to have fixed after all :+1:
