### ISSUE TITLE
Can't parse mosaic definition and mosaic supply change transactions in transaction search

### ISSUE THREAD

**Issue by daoka** [nemtech/symbol-sdk-typescript-javascript#682]
I expect to get these transactions from the transaction search.
https://sym-test.opening-line.jp:3001/transactions/confirmed?embedded=true&signerPublicKey=0F2256DB04AC2E4D94D746CB0F0A66E933A932EE4BFE57C7CA2B80663C84894F&type=16717&type=16973

but, this error occurred when I use SDK.

```
TypeError: Cannot read property 'length' of undefined
    at new UInt64 (/Users/daoka/workspace/labs/symbol-sandbox/node_modules/symbol-sdk/src/model/UInt64.ts:87:23)
    at Function.createFromDTO (/Users/daoka/workspace/labs/symbol-sandbox/node_modules/symbol-sdk/src/model/transaction/Deadline.ts:60:91)
    at CreateStandaloneTransactionFromDTO (/Users/daoka/workspace/labs/symbol-sandbox/node_modules/symbol-sdk/src/infrastructure/transaction/CreateTransactionFromDTO.ts:188:22)
    at exports.CreateTransactionFromDTO (/Users/daoka/workspace/labs/symbol-sandbox/node_modules/symbol-sdk/src/infrastructure/transaction/CreateTransactionFromDTO.ts:552:16)
    at /Users/daoka/workspace/labs/symbol-sandbox/node_modules/symbol-sdk/src/infrastructure/Http.ts:139:29
    at Array.map (<anonymous>)
    at TransactionHttp.toPage (/Users/daoka/workspace/labs/symbol-sandbox/node_modules/symbol-sdk/src/infrastructure/Http.ts:139:18)
    at /Users/daoka/workspace/labs/symbol-sandbox/node_modules/symbol-sdk/src/infrastructure/TransactionHttp.ts:191:19
    at MapSubscriber.project (/Users/daoka/workspace/labs/symbol-sandbox/node_modules/symbol-sdk/src/infrastructure/Http.ts:116:24)
    at MapSubscriber._next (/Users/daoka/workspace/labs/symbol-sandbox/node_modules/rxjs/src/internal/operators/map.ts:84:29)
```

here is the code.

```typescript
const transactionRep = repositoryFactory.createTransactionRepository();
const criteria: TransactionSearchCriteria = {
  group: TransactionGroup.Confirmed,
  signerPublicKey: "0F2256DB04AC2E4D94D746CB0F0A66E933A932EE4BFE57C7CA2B80663C84894F",
  type: [TransactionType.MOSAIC_DEFINITION, TransactionType.MOSAIC_SUPPLY_CHANGE],
  embedded: true,
};

transactionRep.search(criteria).subscribe(
  (x) => {
    console.log(x);
  }, (err) => {
    console.error(err);
  }
);
```

node info
```json
{
  "serverInfo": {
    "restVersion": "2.1.0",
    "sdkVersion": "2.1.0"
  }
}
```

SDK Ver: 0.21.0

**Comment by rg911** [comment]
Thanks for reporting. It is indeed a bug. 
Since the new search endpoint can return only embedded transactions that do not have Deadline and MaxFee (shared with the AggregateTransaction's), the rest payload transform fails. An fix is raised to use the `min` LocalDateTime for embedded transaction deadline.
